// GPL-3.0-only with the additional permission in COPYING.md.
#include "engine/MenuDependency.h"

#include <format>

namespace BetterEnchantmentEffects {
namespace {
constexpr const char *kMenuExports[]{
    "AddSectionItem",
    "ImDrawList_AddCallback",
    "ImDrawList_AddLine",
    "ImDrawList_AddRectFilled",
    "ImDrawList_AddText_FontPtr",
    "ImDrawList_AddText_Vec2",
    "ImDrawList_PopClipRect",
    "ImDrawList_PushClipRect",
    "ImFontGlyphRangesBuilder_AddText",
    "ImGuiInputTextState_GetCursorPos",
    "igAcceptDragDropPayload",
    "igAlignTextToFramePadding",
    "igBeginChild_ID",
    "igBeginChild_Str",
    "igBeginCombo",
    "igBeginDisabled",
    "igBeginDragDropSource",
    "igBeginDragDropTarget",
    "igBeginGroup",
    "igBeginPopup",
    "igBeginPopupModal",
    "igBeginTabBar",
    "igBeginTabItem",
    "igBeginTable",
    "igBulletTextV",
    "igButton",
    "igCalcTextSize",
    "igCheckbox",
    "igCloseCurrentPopup",
    "igCollapsingHeader_BoolPtr",
    "igCollapsingHeader_TreeNodeFlags",
    "igColorButton",
    "igColorPicker3",
    "igDragFloat",
    "igDragFloat3",
    "igDummy",
    "igEndChild",
    "igEndCombo",
    "igEndDisabled",
    "igEndDragDropSource",
    "igEndDragDropTarget",
    "igEndGroup",
    "igEndPopup",
    "igEndTabBar",
    "igEndTabItem",
    "igEndTable",
    "igGetColorU32_Col",
    "igGetColorU32_U32",
    "igGetColorU32_Vec4",
    "igGetContentRegionAvail",
    "igGetCursorPos",
    "igGetCursorPosX",
    "igGetCursorScreenPos",
    "igGetFont",
    "igGetFontSize",
    "igGetForegroundDrawList_Nil",
    "igGetForegroundDrawList_ViewportPtr",
    "igGetForegroundDrawList_WindowPtr",
    "igGetFrameHeight",
    "igGetFrameHeightWithSpacing",
    "igGetIO",
    "igGetItemRectMax",
    "igGetItemRectMin",
    "igGetScrollY",
    "igGetStyle",
    "igGetStyleColorVec4",
    "igGetWindowDrawList",
    "igGetWindowPos",
    "igGetWindowSize",
    "igImage",
    "igImageButton",
    "igIndent",
    "igInputFloat",
    "igInputText",
    "igInputTextWithHint",
    "igIsItemActive",
    "igIsItemDeactivatedAfterEdit",
    "igIsItemHovered",
    "igIsKeyPressed_Bool",
    "igIsKeyPressed_InputFlags",
    "igIsPopupOpen_ID",
    "igIsPopupOpen_Str",
    "igOpenPopup_ID",
    "igOpenPopup_Str",
    "igPlotLines_FloatPtr",
    "igPlotLines_FnFloatPtr",
    "igPopClipRect",
    "igPopID",
    "igPopStyleColor",
    "igPopTextWrapPos",
    "igPushClipRect",
    "igPushID_Int",
    "igPushID_Ptr",
    "igPushID_Str",
    "igPushID_StrStr",
    "igPushStyleColor_U32",
    "igPushStyleColor_Vec4",
    "igPushTextWrapPos",
    "igSameLine",
    "igSelectable_Bool",
    "igSelectable_BoolPtr",
    "igSeparator",
    "igSetCursorPos",
    "igSetCursorPosX",
    "igSetDragDropPayload",
    "igSetKeyboardFocusHere",
    "igSetNextItemWidth",
    "igSetNextWindowSizeConstraints",
    "igSetScrollHereY",
    "igSetScrollY_Float",
    "igSetScrollY_WindowPtr",
    "igSetTooltipV",
    "igSliderFloat",
    "igSliderInt",
    "igSmallButton",
    "igTableHeadersRow",
    "igTableNextColumn",
    "igTableNextRow",
    "igTableSetupColumn",
    "igTextColoredV",
    "igTextDisabledV",
    "igTextUnformatted",
    "igTextV",
    "igTextWrappedV",
    "igTreeNodeV_Ptr",
    "igTreeNodeV_Str",
    "igTreeNode_Str",
    "igTreePop",
    "igUnindent",
};
}

std::span<const char *const> MenuFrameworkExports() { return kMenuExports; }

std::optional<std::string>
CheckMenuFramework(bool a_loaded,
                   const std::function<bool(const char *)> &a_hasExport) {
  if (!a_loaded) {
    return "SKSE Menu Framework is not loaded; editor unavailable. Check its "
           "installation and SKSE loader log, then restart. Recipe playback "
           "does not require the menu.";
  }
  for (const char *name : MenuFrameworkExports()) {
    if (!a_hasExport(name)) {
      return std::format(
          "SKSE Menu Framework is missing export '{}'; editor disabled. "
          "Install a framework release matching this plugin's menu API, then "
          "restart. Recipe playback does not require the menu.",
          name);
    }
  }
  return std::nullopt;
}
}
