file(READ "${SPEC}" spec)
string(JSON name GET "${spec}" name)
string(JSON identity GET "${spec}" identity)
file(READ "${identity}" identity)
string(JSON build GET "${identity}" build)
set(stem "${name}-${build}")
file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${OUTPUT}")

function(create_archive archive)
  set(root "${WORK}/content/${archive}")
  set(names)
  foreach(group IN LISTS ARGN)
    string(JSON count LENGTH "${spec}" ${group})
    math(EXPR last "${count} - 1")
    foreach(index RANGE ${last})
      string(JSON source GET "${spec}" ${group} ${index} source)
      string(JSON destination GET "${spec}" ${group} ${index} destination)
      if(destination IN_LIST names)
        message(FATAL_ERROR "Two package entries write ${destination}")
      endif()
      get_filename_component(folder "${root}/${destination}" DIRECTORY)
      file(MAKE_DIRECTORY "${folder}")
      file(COPY_FILE "${source}" "${root}/${destination}")
      list(APPEND names "${destination}")
    endforeach()
  endforeach()
  list(SORT names)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${WORK}/${archive}" --format=zip
      "--mtime=1980-01-02 00:00:00" -- ${names}
    WORKING_DIRECTORY "${root}" COMMAND_ERROR_IS_FATAL ANY)
endfunction()

create_archive("${stem}.zip" files notices)
create_archive("${stem}-symbols.zip" symbols notices)
set(checksums)
foreach(archive "${stem}.zip" "${stem}-symbols.zip")
  file(SHA256 "${WORK}/${archive}" digest)
  string(APPEND checksums "${digest}  ${archive}\n")
  file(RENAME "${WORK}/${archive}" "${OUTPUT}/${archive}")
  message(STATUS "${OUTPUT}/${archive}")
endforeach()
file(WRITE "${OUTPUT}/${stem}.sha256" "${checksums}")
